import csv
# from config import polling_place_filename
from process_ohio_vf import read_geocoded_from_csv

previously_geocoded = read_geocoded_from_csv()


relevant_attributes = [
	"PARTY_AFFILIATION",
	"PRIMARY-05/07/2019",
	"PRIMARY-09/10/2019",
	"GENERAL-11/05/2019",
	"PRIMARY-03/17/2020",
	"latitude",
	"longitude",
	"Total Pop",
	"Median Income",
	"White Pop",
	"Black Pop",
	"American Indian Pop",
	"Asian Pop",
	"Native Hawaiian Pop",
	"Other Pop",
	"Not Hispanic Pop",
	"Hispanic Pop",
	"No vehicles",
	"1 vehicle",
	"2 vehicles",
	"3 vehicles",
	"4 vehicles",
	"5 or more vehicles",
	"Aggregate vehicles used in commuting",
	"Work commute - Driving",
	"Work commute - Transit",
	"Work commute - Bike",
	"Work commute - Walk",
	"Work commute - Other",
	"Work commute - Work from home",
	"High school diploma",
	"GED",
	"Some college less than 1 year",
	"Some college more than 1 year",
	"Associates degree",
	"Bachelor's degree",
	"Master's degree",
	"Professional school degree",
	"Doctorate degree",
	"Male Pop",
	"Male Pop - Under 5 years",
	"Male Pop - 5-9 years",
	"Male Pop - 10-14 years",
	"Male Pop - 15-17 years",
	"Male Pop - 18-19 years",
	"Male Pop - 20 years",
	"Male Pop - 21 years",
	"Male Pop - 22-24 years",
	"Male Pop - 25-29 years",
	"Male Pop - 30-34 years",
	"Male Pop - 35-39 years",
	"Male Pop - 40-44 years",
	"Male Pop - 45-49 years",
	"Male Pop - 50-54 years",
	"Male Pop - 55-59 years",
	"Male Pop - 60-61 years",
	"Male Pop - 62-64 years",
	"Male Pop - 65-66 years",
	"Male Pop - 67-69 years",
	"Male Pop - 70-74 years",
	"Male Pop - 75-79 years",
	"Male Pop - 80-84 years",
	"Male Pop - 85 years and over",
	"Female Pop",
	"Female Pop - Under 5 years",
	"Female Pop - 5-9 years",
	"Female Pop - 10-14 years",
	"Female Pop - 15-17 years",
	"Female Pop - 18-19 years",
	"Female Pop - 20 years",
	"Female Pop - 21 years",
	"Female Pop - 22-24 years",
	"Female Pop - 25-29 years",
	"Female Pop - 30-34 years",
	"Female Pop - 35-39 years",
	"Female Pop - 40-44 years",
	"Female Pop - 45-49 years",
	"Female Pop - 50-54 years",
	"Female Pop - 55-59 years",
	"Female Pop - 60-61 years",
	"Female Pop - 62-64 years",
	"Female Pop - 65-66 years",
	"Female Pop - 67-69 years",
	"Female Pop - 70-74 years",
	"Female Pop - 75-79 years",
	"Female Pop - 80-84 years",
	"Female Pop - 85 years and over",
	"distance_to_nearest_pp"

]
