outcome = 'voted_2016_11_08'

outcomes = ['voted_2008_02_05', 'voted_2008_07_15', 'voted_2008_11_04', 'voted_2010_07_20', 'voted_2010_11_02', 'voted_2012_03_06', 'voted_2012_07_31', 'voted_2012_11_06', 'voted_2013_11_05', 'voted_2014_05_20', 'voted_2014_11_04', 'voted_2016_03_01', 'voted_2016_03_29', 'voted_2016_05_24', 'voted_2016_07_26', 'voted_2016_11_08', 'voted_2016_12_06', 'voted_2016_12_13', 'voted_2017_01_10', 'voted_2018_01_09', 'voted_2018_01_30', 'voted_2018_02_13', 'voted_2018_03_20', 'voted_2018_04_17', 'voted_2018_05_22', 'voted_2018_06_19', 'voted_2018_07_24', 'voted_2018_08_21', 'voted_2018_11_06', 'voted_2018_12_04']


date_cols = [
	# 'DATE_LAST_VOTED',
	# 'registered_at',
	# 'DATE_ADDED',
]

date_filter_cols = [
	'registered_at',
]

year_cols = [
]

date_as_year_cols = ['dob']

categorical_cols = [
	# 'PARTY_LAST_VOTED',
	'demo',
	'sex',
	# 'census_tract',
	# 'census_block'
	# 'is_active_voter'
	# 'RACE_DESC',
]


totalGenderPopCols = {'Male' : 'tract_geoid$Total_Male_', 'Female' : 'tract_geoid$Total_Female_'}

float_cols = [
	'tract_geoid$Total',
	'tract_geoid$Median_household_income_in_the_past_12_mon',
	'tract_geoid$Total_White_alone',
	'tract_geoid$Total_Black_or_African_American_alone',
	'tract_geoid$Total_American_Indian_and_Alaska_Native_al',
	'tract_geoid$Total_Asian_alone',
	'tract_geoid$Total_Native_Hawaiian_and_Other_Pacific_Is',
	'tract_geoid$Total_Some_other_race_alone',
	'tract_geoid$Total_Not_Hispanic_or_Latino',
	'tract_geoid$Total_Hispanic_or_Latino_',
	'tract_geoid$Total_No_vehicle_available',
	'tract_geoid$Total_1_vehicle_available',
	'tract_geoid$Total_2_vehicles_available',
	'tract_geoid$Total_3_vehicles_available',
	'tract_geoid$Total_4_vehicles_available',
	'tract_geoid$Total_5_or_more_vehicles_available',
	# 'tract_geoid$Aggregate_number_of_vehicles_car,_truck,_o',
	# 'tract_geoid$Total_Car,_truck,_or_van_',
	# 'tract_geoid$Total_Public_transportation_excluding_taxi',
	# 'tract_geoid$Total_Bicycle',
	# 'tract_geoid$Total_Walked',
	# 'tract_geoid$Total_Taxicab,_motorcycle,_or_other_means',
	# 'tract_geoid$Total_Worked_from_home',
	'tract_geoid$Total_Regular_high_school_diploma',
	'tract_geoid$Total_GED_or_alternative_credential',
	'tract_geoid$Total_Some_college,_less_than_1_year',
	'tract_geoid$Total_Some_college,_1_or_more_years,_no_de',
	"tract_geoid$Total_Associate's_degree",
	"tract_geoid$Total_Bachelor's_degree",
	"tract_geoid$Total_Master's_degree",
	'tract_geoid$Total_Professional_school_degree',
	'tract_geoid$Total_Doctorate_degree',
	'tract_geoid$Total_Male_',
	'tract_geoid$Total_Male_Under_5_years',
	'tract_geoid$Total_Male_5_to_9_years',
	'tract_geoid$Total_Male_10_to_14_years',
	'tract_geoid$Total_Male_15_to_17_years',
	'tract_geoid$Total_Male_18_and_19_years',
	'tract_geoid$Total_Male_20_years',
	'tract_geoid$Total_Male_21_years',
	'tract_geoid$Total_Male_22_to_24_years',
	'tract_geoid$Total_Male_25_to_29_years',
	'tract_geoid$Total_Male_30_to_34_years',
	'tract_geoid$Total_Male_35_to_39_years',
	'tract_geoid$Total_Male_40_to_44_years',
	'tract_geoid$Total_Male_45_to_49_years',
	'tract_geoid$Total_Male_50_to_54_years',
	'tract_geoid$Total_Male_55_to_59_years',
	'tract_geoid$Total_Male_60_and_61_years',
	'tract_geoid$Total_Male_62_to_64_years',
	'tract_geoid$Total_Male_65_and_66_years',
	'tract_geoid$Total_Male_67_to_69_years',
	'tract_geoid$Total_Male_70_to_74_years',
	'tract_geoid$Total_Male_75_to_79_years',
	'tract_geoid$Total_Male_80_to_84_years',
	'tract_geoid$Total_Male_85_years_and_over',
	'tract_geoid$Total_Female_',
	'tract_geoid$Total_Female_Under_5_years',
	'tract_geoid$Total_Female_5_to_9_years',
	'tract_geoid$Total_Female_10_to_14_years',
	'tract_geoid$Total_Female_15_to_17_years',
	'tract_geoid$Total_Female_18_and_19_years',
	'tract_geoid$Total_Female_20_years',
	'tract_geoid$Total_Female_21_years',
	'tract_geoid$Total_Female_22_to_24_years',
	'tract_geoid$Total_Female_25_to_29_years',
	'tract_geoid$Total_Female_30_to_34_years',
	'tract_geoid$Total_Female_35_to_39_years',
	'tract_geoid$Total_Female_40_to_44_years',
	'tract_geoid$Total_Female_45_to_49_years',
	'tract_geoid$Total_Female_50_to_54_years',
	'tract_geoid$Total_Female_55_to_59_years',
	'tract_geoid$Total_Female_60_and_61_years',
	'tract_geoid$Total_Female_62_to_64_years',
	'tract_geoid$Total_Female_65_and_66_years',
	'tract_geoid$Total_Female_67_to_69_years',
	'tract_geoid$Total_Female_70_to_74_years',
	'tract_geoid$Total_Female_75_to_79_years',
	'tract_geoid$Total_Female_80_to_84_years',
	'tract_geoid$Total_Female_85_years_and_over',
	'tract_geoid$ALAND',
	'dist_to_pollingLocation',
	# 'dist_to_dropOffLocation',
	# 'dist_to_earlyVoteSite',
]

def get_min_age(colName,col_type):
		if 'Under' in colName:
			minAge = 0
		elif 'over' in colName:
			minAge=  85
		else:
			minAge = int(colName.split(col_type)[1].split('_',1)[0])
		return minAge

def getFractionCols(ages = [ 0, 18, 62, 1000]):
	sumCols = {
		f'fraction_{gender}_{ages[i]}_{ages[i+1]}' : []
		for gender in ('Male','Female')
		for i in range(len(ages)-1)
	}
	for gender in ('Male', 'Female'):
		col_type = f'tract_geoid$Total_{gender}_'
		age_cols = [col for col in float_cols if col_type in col and col_type != col]
		for col in age_cols:
			minAge = get_min_age(col,col_type)
			for i, age in enumerate(ages):
				if minAge < age:
					sumCols[f'fraction_{gender}_{ages[i-1]}_{ages[i]}'].append(col)
					break
		sumCols[f'fraction_{gender}'] = [col_type]

	sumCols[f'fraction_no_vehicles'] = ['tract_geoid$Total_No_vehicle_available']
	sumCols[f'fraction_some_vehicle'] = [
		'tract_geoid$Total_No_vehicle_available',
		'tract_geoid$Total_1_vehicle_available',
		'tract_geoid$Total_2_vehicles_available',
		'tract_geoid$Total_3_vehicles_available',
		'tract_geoid$Total_4_vehicles_available',
		'tract_geoid$Total_5_or_more_vehicles_available',
	]
	sumCols['fraction_no_college'] = [
		'tract_geoid$Total_Regular_high_school_diploma',
		'tract_geoid$Total_GED_or_alternative_credential',
	]
	sumCols['fraction_some_college'] = [
		'tract_geoid$Total_Some_college,_less_than_1_year',
		'tract_geoid$Total_Some_college,_1_or_more_years,_no_de',
		"tract_geoid$Total_Associate's_degree",
		"tract_geoid$Total_Bachelor's_degree",
		"tract_geoid$Total_Master's_degree",
		'tract_geoid$Total_Professional_school_degree',
		'tract_geoid$Total_Doctorate_degree',
	]
	raceCols = [
		'tract_geoid$Total_White_alone',
		'tract_geoid$Total_Black_or_African_American_alone',
		'tract_geoid$Total_American_Indian_and_Alaska_Native_al',
		'tract_geoid$Total_Asian_alone',
		'tract_geoid$Total_Native_Hawaiian_and_Other_Pacific_Is',
		'tract_geoid$Total_Some_other_race_alone',
		'tract_geoid$Total_Not_Hispanic_or_Latino',
		'tract_geoid$Total_Hispanic_or_Latino_',
	]
	for raceCol in raceCols:
		race = raceCol.split('tract_geoid$Total_')[1]
		sumCols[f'fraction_{race}'] = [raceCol]
	return sumCols

fractionCols = getFractionCols()



log_reg_cols = date_cols + year_cols + categorical_cols + float_cols + date_as_year_cols + date_filter_cols
log_reg_cols_and_outcome = log_reg_cols + [outcome]
log_reg_cols_without_outcome = [col for col in log_reg_cols_and_outcome if col != outcome]

# potential_log_reg_cols = [
# 	'BIRTHDATE',
# 	'REGISTRATION_DATE',
# 	'RACE',
# 	'GENDER',
# 	'PARTY_LAST_VOTED',
# 	'DATE_ADDED',
# 	'RACE_DESC',
# 	'tract_geoid$Total',
# 	'tract_geoid$Median_household_income_in_the_past_12_mon',
# 	'tract_geoid$Total_White_alone',
# 	'tract_geoid$Total_Black_or_African_American_alone',
# 	'tract_geoid$Total_American_Indian_and_Alaska_Native_al',
# 	'tract_geoid$Total_Asian_alone',
# 	'tract_geoid$Total_Native_Hawaiian_and_Other_Pacific_Is',
# 	'tract_geoid$Total_Some_other_race_alone',
# 	'tract_geoid$Total_Not_Hispanic_or_Latino',
# 	'tract_geoid$Total_Hispanic_or_Latino_',
# 	'tract_geoid$Total_No_vehicle_available',
# 	'tract_geoid$Total_1_vehicle_available',
# 	'tract_geoid$Total_2_vehicles_available',
# 	'tract_geoid$Total_3_vehicles_available',
# 	'tract_geoid$Total_4_vehicles_available',
# 	'tract_geoid$Total_5_or_more_vehicles_available',
# 	'tract_geoid$Aggregate_number_of_vehicles_car,_truck,_o',
# 	'tract_geoid$Total_Car,_truck,_or_van_',
# 	'tract_geoid$Total_Public_transportation_excluding_taxi',
# 	'tract_geoid$Total_Bicycle',
# 	'tract_geoid$Total_Walked',
# 	'tract_geoid$Total_Taxicab,_motorcycle,_or_other_means',
# 	'tract_geoid$Total_Worked_from_home',
# 	'tract_geoid$Total_Regular_high_school_diploma',
# 	'tract_geoid$Total_GED_or_alternative_credential',
# 	'tract_geoid$Total_Some_college,_less_than_1_year',
# 	'tract_geoid$Total_Some_college,_1_or_more_years,_no_de',
# 	"tract_geoid$Total_Associate's_degree",
# 	"tract_geoid$Total_Bachelor's_degree",
# 	"tract_geoid$Total_Master's_degree",
# 	'tract_geoid$Total_Professional_school_degree',
# 	'tract_geoid$Total_Doctorate_degree',
# 	'tract_geoid$Total_Male_',
# 	'tract_geoid$Total_Male_Under_5_years',
# 	'tract_geoid$Total_Male_5_to_9_years',
# 	'tract_geoid$Total_Male_10_to_14_years',
# 	'tract_geoid$Total_Male_15_to_17_years',
# 	'tract_geoid$Total_Male_18_and_19_years',
# 	'tract_geoid$Total_Male_20_years',
# 	'tract_geoid$Total_Male_21_years',
# 	'tract_geoid$Total_Male_22_to_24_years',
# 	'tract_geoid$Total_Male_25_to_29_years',
# 	'tract_geoid$Total_Male_30_to_34_years',
# 	'tract_geoid$Total_Male_35_to_39_years',
# 	'tract_geoid$Total_Male_40_to_44_years',
# 	'tract_geoid$Total_Male_45_to_49_years',
# 	'tract_geoid$Total_Male_50_to_54_years',
# 	'tract_geoid$Total_Male_55_to_59_years',
# 	'tract_geoid$Total_Male_60_and_61_years',
# 	'tract_geoid$Total_Male_62_to_64_years',
# 	'tract_geoid$Total_Male_65_and_66_years',
# 	'tract_geoid$Total_Male_67_to_69_years',
# 	'tract_geoid$Total_Male_70_to_74_years',
# 	'tract_geoid$Total_Male_75_to_79_years',
# 	'tract_geoid$Total_Male_80_to_84_years',
# 	'tract_geoid$Total_Male_85_years_and_over',
# 	'tract_geoid$Total_Female_',
# 	'tract_geoid$Total_Female_Under_5_years',
# 	'tract_geoid$Total_Female_5_to_9_years',
# 	'tract_geoid$Total_Female_10_to_14_years',
# 	'tract_geoid$Total_Female_15_to_17_years',
# 	'tract_geoid$Total_Female_18_and_19_years',
# 	'tract_geoid$Total_Female_20_years',
# 	'tract_geoid$Total_Female_21_years',
# 	'tract_geoid$Total_Female_22_to_24_years',
# 	'tract_geoid$Total_Female_25_to_29_years',
# 	'tract_geoid$Total_Female_30_to_34_years',
# 	'tract_geoid$Total_Female_35_to_39_years',
# 	'tract_geoid$Total_Female_40_to_44_years',
# 	'tract_geoid$Total_Female_45_to_49_years',
# 	'tract_geoid$Total_Female_50_to_54_years',
# 	'tract_geoid$Total_Female_55_to_59_years',
# 	'tract_geoid$Total_Female_60_and_61_years',
# 	'tract_geoid$Total_Female_62_to_64_years',
# 	'tract_geoid$Total_Female_65_and_66_years',
# 	'tract_geoid$Total_Female_67_to_69_years',
# 	'tract_geoid$Total_Female_70_to_74_years',
# 	'tract_geoid$Total_Female_75_to_79_years',
# 	'tract_geoid$Total_Female_80_to_84_years',
# 	'tract_geoid$Total_Female_85_years_and_over',
# 	'dist_to_pollingLocation',
# 	'dist_to_dropOffLocation',
# 	'dist_to_earlyVoteSite',
# ]


# all_cols = [
# 	'COUNTY_CODE',
# 	'REGISTRATION_NUMBER',
# 	'VOTER_STATUS',
# 	'LAST_NAME',
# 	'FIRST_NAME',
# 	'MIDDLE_MAIDEN_NAME',
# 	'NAME_SUFFIX',
# 	'NAME_TITLE',
# 	'RESIDENCE_HOUSE_NUMBER',
# 	'RESIDENCE_STREET_NAME',
# 	'RESIDENCE_STREET_SUFFIX',
# 	'RESIDENCE_APT_UNIT_NBR',
# 	'RESIDENCE_CITY',
# 	'RESIDENCE_ZIPCODE',
# 	'BIRTHDATE',
# 	'REGISTRATION_DATE',
# 	'RACE',
# 	'GENDER',
# 	'LAND_DISTRICT',
# 	'LAND_LOT',
# 	'sTATUS_REASON',
# 	'COUNTY_PRECINCT_ID',
# 	'CITY_PRECINCT_ID',
# 	'CONGRESSIONAL_DISTRICT',
# 	'sENATE_DISTRICT',
# 	'HOUSE_DISTRICT',
# 	'JUDICIAL_DISTRICT',
# 	'COMMISSION_DISTRICT',
# 	'sCHOOL_DISTRICT',
# 	'COUNTY_DISTRICTA_NAME',
# 	'COUNTY_DISTRICTA_VALUE',
# 	'COUNTY_DISTRICTB_NAME',
# 	'COUNTY_DISTRICTB_VALUE',
# 	'MUNICIPAL_NAME',
# 	'MUNICIPAL_CODE',
# 	'WARD_CITY_COUNCIL_NAME',
# 	'WARD_CITY_COUNCIL_CODE',
# 	'CITY_SCHOOL_DISTRICT_NAME',
# 	'CITY_SCHOOL_DISTRICT_VALUE',
# 	'CITY_DISTA_NAME',
# 	'CITY_DISTA_VALUE',
# 	'CITY_DISTB_NAME',
# 	'CITY_DISTB_VALUE',
# 	'CITY_DISTC_NAME',
# 	'CITY_DISTC_VALUE',
# 	'CITY_DISTD_NAME',
# 	'CITY_DISTD_VALUE',
# 	'DATE_LAST_VOTED',
# 	'PARTY_LAST_VOTED',
# 	'DATE_ADDED',
# 	'DATE_CHANGED',
# 	'DISTRICT_COMBO',
# 	'RACE_DESC',
# 	'LAST_CONTACT_DATE',
# 	'MAIL_HOUSE_NBR',
# 	'MAIL_STREET_NAME',
# 	'MAIL_APT_UNIT_NBR',
# 	'MAIL_CITY',
# 	'MAIL_STATE',
# 	'MAIL_ZIPCODE',
# 	'MAIL_ADDRESS_2',
# 	'MAIL_ADDRESS_3',
# 	'MAIL_COUNTRY',
# 	'geocode_source',
# 	'latitude',
# 	'longitude',
# 	'census_state',
# 	'census_county',
# 	'census_tract',
# 	'census_block',
# 	'tract_geoid',
# 	'closest_pollingLocation',
# 	'closest_dropOffLocation',
# 	'closest_earlyVoteSite',
# 	'dist_to_pollingLocation',
# 	'dist_to_dropOffLocation',
# 	'dist_to_earlyVoteSite',
# 	'tract_geoid$index',
# 	'tract_geoid$Total',
# 	'tract_geoid$Median_household_income_in_the_past_12_mon',
# 	'tract_geoid$Total_White_alone',
# 	'tract_geoid$Total_Black_or_African_American_alone',
# 	'tract_geoid$Total_American_Indian_and_Alaska_Native_al',
# 	'tract_geoid$Total_Asian_alone',
# 	'tract_geoid$Total_Native_Hawaiian_and_Other_Pacific_Is',
# 	'tract_geoid$Total_Some_other_race_alone',
# 	'tract_geoid$Total_Not_Hispanic_or_Latino',
# 	'tract_geoid$Total_Hispanic_or_Latino_',
# 	'tract_geoid$Total_No_vehicle_available',
# 	'tract_geoid$Total_1_vehicle_available',
# 	'tract_geoid$Total_2_vehicles_available',
# 	'tract_geoid$Total_3_vehicles_available',
# 	'tract_geoid$Total_4_vehicles_available',
# 	'tract_geoid$Total_5_or_more_vehicles_available',
# 	'tract_geoid$Aggregate_number_of_vehicles_car,_truck,_o',
# 	'tract_geoid$Total_Car,_truck,_or_van_',
# 	'tract_geoid$Total_Public_transportation_excluding_taxi',
# 	'tract_geoid$Total_Bicycle',
# 	'tract_geoid$Total_Walked',
# 	'tract_geoid$Total_Taxicab,_motorcycle,_or_other_means',
# 	'tract_geoid$Total_Worked_from_home',
# 	'tract_geoid$Total_Regular_high_school_diploma',
# 	'tract_geoid$Total_GED_or_alternative_credential',
# 	'tract_geoid$Total_Some_college,_less_than_1_year',
# 	'tract_geoid$Total_Some_college,_1_or_more_years,_no_de',
# 	"tract_geoid$Total_Associate's_degree",
# 	"tract_geoid$Total_Bachelor's_degree",
# 	"tract_geoid$Total_Master's_degree",
# 	'tract_geoid$Total_Professional_school_degree',
# 	'tract_geoid$Total_Doctorate_degree',
# 	'tract_geoid$Total_Male_',
# 	'tract_geoid$Total_Male_Under_5_years',
# 	'tract_geoid$Total_Male_5_to_9_years',
# 	'tract_geoid$Total_Male_10_to_14_years',
# 	'tract_geoid$Total_Male_15_to_17_years',
# 	'tract_geoid$Total_Male_18_and_19_years',
# 	'tract_geoid$Total_Male_20_years',
# 	'tract_geoid$Total_Male_21_years',
# 	'tract_geoid$Total_Male_22_to_24_years',
# 	'tract_geoid$Total_Male_25_to_29_years',
# 	'tract_geoid$Total_Male_30_to_34_years',
# 	'tract_geoid$Total_Male_35_to_39_years',
# 	'tract_geoid$Total_Male_40_to_44_years',
# 	'tract_geoid$Total_Male_45_to_49_years',
# 	'tract_geoid$Total_Male_50_to_54_years',
# 	'tract_geoid$Total_Male_55_to_59_years',
# 	'tract_geoid$Total_Male_60_and_61_years',
# 	'tract_geoid$Total_Male_62_to_64_years',
# 	'tract_geoid$Total_Male_65_and_66_years',
# 	'tract_geoid$Total_Male_67_to_69_years',
# 	'tract_geoid$Total_Male_70_to_74_years',
# 	'tract_geoid$Total_Male_75_to_79_years',
# 	'tract_geoid$Total_Male_80_to_84_years',
# 	'tract_geoid$Total_Male_85_years_and_over',
# 	'tract_geoid$Total_Female_',
# 	'tract_geoid$Total_Female_Under_5_years',
# 	'tract_geoid$Total_Female_5_to_9_years',
# 	'tract_geoid$Total_Female_10_to_14_years',
# 	'tract_geoid$Total_Female_15_to_17_years',
# 	'tract_geoid$Total_Female_18_and_19_years',
# 	'tract_geoid$Total_Female_20_years',
# 	'tract_geoid$Total_Female_21_years',
# 	'tract_geoid$Total_Female_22_to_24_years',
# 	'tract_geoid$Total_Female_25_to_29_years',
# 	'tract_geoid$Total_Female_30_to_34_years',
# 	'tract_geoid$Total_Female_35_to_39_years',
# 	'tract_geoid$Total_Female_40_to_44_years',
# 	'tract_geoid$Total_Female_45_to_49_years',
# 	'tract_geoid$Total_Female_50_to_54_years',
# 	'tract_geoid$Total_Female_55_to_59_years',
# 	'tract_geoid$Total_Female_60_and_61_years',
# 	'tract_geoid$Total_Female_62_to_64_years',
# 	'tract_geoid$Total_Female_65_and_66_years',
# 	'tract_geoid$Total_Female_67_to_69_years',
# 	'tract_geoid$Total_Female_70_to_74_years',
# 	'tract_geoid$Total_Female_75_to_79_years',
# 	'tract_geoid$Total_Female_80_to_84_years',
# 	'tract_geoid$Total_Female_85_years_and_over',
# 	'tract_geoid$GEO_ID',
# 	'tract_geoid$NAME',
# 	'tract_geoid$state',
# 	'tract_geoid$county',
# 	'tract_geoid$tract',
# 	'closest_pollingLocation$pp_identifier',
# 	'closest_pollingLocation$latitude',
# 	'closest_pollingLocation$longitude',
# 	'closest_pollingLocation$placeType',
# 	'closest_pollingLocation$addressLocationname',
# 	'closest_pollingLocation$addressLine1',
# 	'closest_pollingLocation$addressCity',
# 	'closest_pollingLocation$addressState',
# 	'closest_pollingLocation$addressZip',
# 	'closest_pollingLocation$sources0Name',
# 	'closest_pollingLocation$sources0Official',
# 	'closest_pollingLocation$addressLine2',
# 	'closest_pollingLocation$pollingHours',
# 	'closest_pollingLocation$startDate',
# 	'closest_pollingLocation$endDate',
# 	'closest_pollingLocation$notes',
# 	'closest_pollingLocation$filename',
# 	'closest_pollingLocation$metro',
# 	'closest_pollingLocation$spacing',
# 	'closest_pollingLocation$query_version',
# 	'closest_dropOffLocation$pp_identifier',
# 	'closest_dropOffLocation$latitude',
# 	'closest_dropOffLocation$longitude',
# 	'closest_dropOffLocation$placeType',
# 	'closest_dropOffLocation$addressLocationname',
# 	'closest_dropOffLocation$addressLine1',
# 	'closest_dropOffLocation$addressCity',
# 	'closest_dropOffLocation$addressState',
# 	'closest_dropOffLocation$addressZip',
# 	'closest_dropOffLocation$sources0Name',
# 	'closest_dropOffLocation$sources0Official',
# 	'closest_dropOffLocation$addressLine2',
# 	'closest_dropOffLocation$pollingHours',
# 	'closest_dropOffLocation$startDate',
# 	'closest_dropOffLocation$endDate',
# 	'closest_dropOffLocation$notes',
# 	'closest_dropOffLocation$filename',
# 	'closest_dropOffLocation$metro',
# 	'closest_dropOffLocation$spacing',
# 	'closest_dropOffLocation$query_version',
# 	'closest_earlyVoteSite$pp_identifier',
# 	'closest_earlyVoteSite$latitude',
# 	'closest_earlyVoteSite$longitude',
# 	'closest_earlyVoteSite$placeType',
# 	'closest_earlyVoteSite$addressLocationname',
# 	'closest_earlyVoteSite$addressLine1',
# 	'closest_earlyVoteSite$addressCity',
# 	'closest_earlyVoteSite$addressState',
# 	'closest_earlyVoteSite$addressZip',
# 	'closest_earlyVoteSite$sources0Name',
# 	'closest_earlyVoteSite$sources0Official',
# 	'closest_earlyVoteSite$addressLine2',
# 	'closest_earlyVoteSite$pollingHours',
# 	'closest_earlyVoteSite$startDate',
# 	'closest_earlyVoteSite$endDate',
# 	'closest_earlyVoteSite$notes',
# 	'closest_earlyVoteSite$filename',
# 	'closest_earlyVoteSite$metro',
# 	'closest_earlyVoteSite$spacing',
# 	'closest_earlyVoteSite$query_version',
# ]
